/**
 * Curated wordlists for memorable site ids (spec: exhibit titles +
 * memorable subdomains). Both lists are EXACTLY 256 entries — one random
 * byte indexes each with zero modulo bias — lowercase a–z, 3–8 chars,
 * concrete and content-neutral. Never remove or reorder casually: ids are
 * validated by shape only, so edits here are safe, but 256-ness is load-
 * bearing (see core-libs test).
 */

export const ADJECTIVES: readonly string[] = [
  "able", "agile", "airy", "amber", "ample", "aqua", "arbor", "ashen",
  "auric", "azure", "balmy", "beryl", "blithe", "bold", "bonny", "brave",
  "breezy", "brief", "bright", "brisk", "bronze", "burly", "calm", "candid",
  "canny", "cedar", "cheery", "chief", "chill", "civic", "classic", "clean",
  "clear", "clever", "cobalt", "cocoa", "copper", "coral", "cosmic", "cozy",
  "crisp", "damson", "dandy", "dapper", "deft", "dewy", "docile", "dual",
  "dusky", "dusty", "eager", "early", "earthen", "ebony", "elder", "elfin",
  "emerald", "equal", "extra", "fabled", "fair", "famed", "fancy", "fast",
  "festive", "fine", "firm", "fleet", "floral", "fluent", "fluffy", "fond",
  "frank", "free", "fresh", "frosty", "frugal", "funky", "fuzzy", "gentle",
  "gilded", "glad", "glossy", "golden", "grand", "green", "hale", "handy",
  "happy", "hardy", "hazel", "hearty", "hidden", "high", "honest", "humble",
  "icy", "ideal", "indigo", "inky", "ivory", "jade", "jaunty", "jolly",
  "jovial", "keen", "kind", "kindly", "lively", "local", "lofty", "loyal",
  "lucent", "lucid", "lucky", "lunar", "lush", "magic", "main", "major",
  "mellow", "merry", "mild", "minty", "modest", "mossy", "neat", "nifty",
  "nimble", "noble", "north", "novel", "oaken", "ochre", "olive", "opal",
  "open", "oval", "pale", "peachy", "pearly", "plaid", "plucky", "plum",
  "polar", "poised", "proud", "pure", "quick", "quiet", "rapid", "rare",
  "regal", "ripe", "roan", "robust", "rosy", "round", "royal", "ruby",
  "ruddy", "rural", "russet", "rustic", "sable", "safe", "sage", "sandy",
  "scenic", "sepia", "serene", "sharp", "shiny", "silent", "silken", "silver",
  "simple", "sleek", "slick", "smart", "smooth", "snowy", "snug", "sober",
  "solar", "solid", "sound", "spare", "spry", "stable", "starry", "steady",
  "sterling", "stout", "striped", "strong", "sturdy", "suave", "subtle", "sunny",
  "super", "swift", "tan", "tawny", "teal", "tidy", "timely", "tonal",
  "topaz", "tranquil", "trim", "true", "trusty", "tweed", "umber", "upbeat",
  "urban", "valiant", "velvet", "verdant", "vivid", "warm", "wavy", "whole",
  "wide", "wild", "wise", "witty", "wooden", "woolly", "worthy", "young",
  "zesty", "zippy", "amiable", "ancient", "artful", "astute", "blissful", "brainy",
  "bubbly", "casual", "chipper", "citrus", "comfy", "cordial", "crimson", "daring",
  "deep", "direct", "earnest", "easy", "elegant", "faded", "gallant", "graceful",
];

export const NOUNS: readonly string[] = [
  "acorn", "alder", "anchor", "apple", "aspen", "atoll", "aurora", "badge",
  "bamboo", "banjo", "barley", "basin", "bay", "beach", "beacon", "bear",
  "beech", "bell", "berry", "birch", "bison", "bloom", "bluff", "breeze",
  "bridge", "brook", "cabin", "cairn", "canoe", "canyon", "cape", "castle",
  "cave", "chalk", "cherry", "cliff", "cloud", "clover", "coast", "comet",
  "compass", "cove", "crane", "crater", "creek", "crest", "crocus", "curlew",
  "cypress", "dahlia", "dale", "deer", "delta", "dome", "dove", "drift",
  "dune", "eagle", "echo", "eddy", "elk", "elm", "ember", "falcon",
  "fawn", "fern", "field", "finch", "fjord", "flint", "flute", "fog",
  "forest", "forge", "fossil", "fox", "garden", "garnet", "gazebo", "geyser",
  "glacier", "glade", "glen", "grove", "gull", "harbor", "haven", "hawk",
  "heath", "hedge", "heron", "hill", "hollow", "horizon", "ibis", "inlet",
  "iris", "island", "isle", "ivy", "jasper", "jetty", "juniper", "kelp",
  "kite", "knoll", "lagoon", "lake", "lantern", "larch", "lark", "laurel",
  "lava", "leaf", "ledge", "lemon", "lichen", "lilac", "lily", "linden",
  "lotus", "lynx", "maple", "marsh", "meadow", "mesa", "mist", "moor",
  "moss", "moth", "mount", "myrtle", "nectar", "nest", "newt", "night",
  "nook", "oak", "oasis", "ocean", "orchard", "oriole", "osprey", "otter",
  "owl", "palm", "path", "peak", "pebble", "pecan", "peony", "pier",
  "pine", "plaza", "plume", "pond", "poplar", "poppy", "prairie", "quail",
  "quarry", "quartz", "quay", "rain", "raven", "reef", "ridge", "river",
  "robin", "rock", "rowan", "rune", "sail", "salmon", "sea", "sequoia",
  "shell", "shore", "shrub", "sierra", "sky", "slate", "sloop", "sorrel",
  "spark", "sparrow", "spring", "spruce", "sprout", "spur", "star", "stone",
  "storm", "stream", "summit", "sun", "swale", "swan", "sycamore", "tarn",
  "teak", "tern", "thicket", "thistle", "thorn", "tide", "trail", "tree",
  "trout", "tulip", "tundra", "vale", "valley", "vine", "violet", "walnut",
  "wave", "willow", "wind", "wolf", "wren", "yarrow", "zephyr", "zinnia",
  "acacia", "badger", "bramble", "briar", "brine", "bunting", "burrow", "butte",
  "cascade", "channel", "cobble", "condor", "coppice", "cosmos", "cotton", "crag",
  "cress", "dell", "desert", "dingle", "dory", "drake", "drumlin", "dusk",
  "estuary", "fen", "firth", "foam", "frost", "galaxy", "gorge", "grotto",
];
